chore: fix release #10

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,24 +20,48 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Set up JDK 17
+      - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
-          java-version: "17"
-          distribution: "temurin"
+          java-version: "11"
+      - name: maven-settings
+        uses: s4u/maven-settings-action@v2
+        with:
+          servers: '[{"id": "github", "username": "${{ github.repository_owner }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
 
       - name: Install dependencies
         run: mvn validate
 
       - name: Build and Test
-        run: mvn validate
+        run: mvn clean install
 
       - name: Release
-        uses: qcastel/github-actions-maven-release@master
-        env:
-          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
-        with:
-          release-branch-name: "main"
+        run: |
+          if [[ "${{ inputs.environment }}" == "major" ]]; then
+              echo "Increase the major version."
+              
+              MAVEN_OPTION="$MAVEN_OPTION -DdevelopmentVersion=\${parsedVersion.nextMajorVersion}.0.0-SNAPSHOT"
+          elif [[ "${{ inputs.environment }}" == "minor" ]]; then
+              echo "Increase the minor version."
+              
+              MAVEN_OPTION="$MAVEN_OPTION -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT"
+          else
+              echo "Increase the patch version."
+              
+              MAVEN_OPTION="$MAVEN_OPTION -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT"
+          fi
 
-          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"
-          maven-servers: '[{"id": "github", "username": "${{ github.repository_owner }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
+          echo "Do mvn release:prepare with options $MAVEN_OPTION"
+          mvn $MAVEN_OPTION build-helper:parse-version release:prepare -B
+
+          # do release if prepare did not fail
+          if [[ ("$?" -eq 0) && ($SKIP_PERFORM == "false") ]]; then
+            echo "Do mvn release:perform with options $MAVEN_OPTION"
+            mvn $MAVEN_OPTION build-helper:parse-version release:perform -B"
+          fi
+
+          # rollback release if prepare or perform failed
+          if [[ "$?" -ne 0 ]] ; then
+            echo "Rolling back release after failure"
+            mvn $MAVEN_OPTION release:rollback -B"
+          fi
